### ISSUE TITLE
Does not highlight symbols when using #if statements

### ISSUE THREAD

**Issue by guidedways** [chiahsien/AutoHighlightSymbol#8]
I've got a bunch of code that I block out using statements like:
# if !TARGET_OS_IPHONE

...
# elif TARGET_OS_IPHONE

...
# endif

It seems that the plugin randomly misses out on symbols that are in fact 'active'.

**Comment by chiahsien** [comment]
This plugin gets symbols from Xcode, so it is probably due to Xcode issue.
- Is your code fully indexed by Xcode?
- When you put the cursor on a symbol, is there a dash line under the symbol?
- Maybe `Clean` or `Delete DerivedData` then `Build` can fix the issue?
